version: "3.8"
services:
  db:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

  api:
    container_name: hangout-api

    restart: always
    build:
      context: .
    env_file: ./.env
    command: node index
    image: hangout-api
    depends_on:
      - db
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - PORT=$PORT
    links:
      - db
    volumes:
      - .:/app/
      - /app/node_modules

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql:
  mysql_config:
